services:
  db:
    image: postgres:17
    container_name: emt-postgres
    restart: always
    environment:
      POSTGRES_DB: emt_book
      POSTGRES_USER: emt
      POSTGRES_PASSWORD: emt
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: emt-backend
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/emt_book
      SPRING_DATASOURCE_USERNAME: emt
      SPRING_DATASOURCE_PASSWORD: emt
    ports:
      - "9090:8080"
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: emt-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: always

volumes:
  pgdata:
